### ISSUE TITLE
Error: unknown command "env" for "circleci"

### ISSUE THREAD

**Issue by Elte156** [CircleCI-Public/browser-tools-orb#117]
### Orb version

1.4.9

### What happened

Using sample circle ci config:

```yaml
    docker:
      - image: cimg/node:18.20-browsers
    steps:
      - browser-tools/install-chrome
```

Results in:

```console
Error: unknown command "env" for "circleci"
Run 'circleci --help' for usage.
ERRO[0000] Exit with status 1 due to generic error       error="unknown command \"env\" for \"circleci\""

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

- It should install chrome without issue
- Note: 1.4.8 did not have this issue

**Comment by marboledacci** [comment]
Could you provide more more details? Any step previous to that or specific configuration you have made.
I've been running that workflow, with the same image and the same orb version and it always works.

**Comment by Elte156** [comment]
@marboledacci let me try to recreate the issue with a full `config.yml` example for you.

**Comment by Elte156** [comment]
Here's a full `config.yml` that results in error

```yml
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1

jobs:
  test_job:
    docker:
      - image: cimg/node:18.20-browsers
    steps:
      - run:
          command: |
            circleci --help
            circleci version
      - browser-tools/install-chrome

workflows:
  pull_request:
    jobs:
      - test_job:
          filters:
            branches:
              ignore: [main]
```

The "compiled source" says:
`# Orb 'circleci/browser-tools@1' resolved to 'circleci/browser-tools@1.4.9'`

The output is:
```console
The CLI tool to be used in CircleCI.

Usage:
  circleci [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Validate and update the circleCI configuration file
  execute     Run a job in a container on the local machine
  help        Help about any command
  task        Manage tasks
  tests       Collect and split tests so they may be run in parallel.
  version     Output version info

Flags:
  -h, --help      help for circleci
      --verbose   enable verbose logging output

Use "circleci [command] --help" for more information about a command.
INFO[0000] Clean exit without errors                    
Build Agent version: 1.0.213497-server-4.2-0f31974a
Built: 2023-12-14T20:14:42+0000
CircleCI received exit code 0


---


Error: unknown command "env" for "circleci"
Run 'circleci --help' for usage.
ERRO[0000] Exit with status 1 due to generic error       error="unknown command \"env\" for \"circleci\""

Exited with code exit status 1
CircleCI received exit code 1

```

@marboledacci based on these findings:
- I'm guessing your `Build Agent version` is different
- My `circleci` cli does not offer an `env` command
- [This is the breaking change](https://github.com/CircleCI-Public/browser-tools-orb/blob/22701d0e43603d3513749708cb2bbed3bb61a89f/src/scripts/install-chrome.sh#L5) introduced in orb version 1.4.9 - PR #72
