### ISSUE TITLE
Step Install Firefox with `use_cache` fails on new release

### ISSUE THREAD

**Issue by dcsaszar** [CircleCI-Public/browser-tools-orb#120]
### Orb version
1.5.0

### What happened

We added `use_cache` to the Firefox install step a few weeks ago (FF version 133).

```yaml
          steps:
            - browser-tools/install-firefox:
                use_cache: true
```

When a new version (134.0.0) came out, the CI constantly failed with `BAD signature`.
Assuming this was a one-off, we changed the step to
```yaml
          steps:
            - browser-tools/install-firefox:
                cache_key: v2
                use_cache: true
```

But now a new version came out and we have the same error:

```
System detected as Linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   711  100   711    0     0  10043      0 --:--:-- --:--:-- --:--:-- 10157
Latest stable version of Firefox is 134.0.1
^@^@gpg: Signature made Mon 13 Jan 2025 04:51:38 PM UTC
gpg:                using RSA key ADD7079479700DCADFDD5337E36D3B13F3D93274
gpg: Good signature from "Mozilla Software Releases <release@mozilla.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 14F2 6682 D091 6CDD 81E3  7B6D 61B7 B526 D98F 0353
     Subkey fingerprint: ADD7 0794 7970 0DCA DFDD  5337 E36D 3B13 F3D9 3274
Cache found.
gpg: Signature made Mon 13 Jan 2025 02:17:26 PM UTC
gpg:                using RSA key ADD7079479700DCADFDD5337E36D3B13F3D93274
gpg: BAD signature from "Mozilla Software Releases <release@mozilla.com>" [unknown]

Exited with code exit status 1

CircleCI received exit code 1
```

### Expected behavior

Installing FF should not fail with `use_cache`.
