### ISSUE TITLE
Not able to install Google Chrome in Mac Executor

### ISSUE THREAD

**Issue by abhinaba-ghosh** [CircleCI-Public/browser-tools-orb#44]
### Orb version
circleci/browser-tools@1.2.5

### What happened
The Job - 
```
steps:
  - checkout
  - macos/add-uitest-permissions
  - run: 
       command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget
        name: 'Install wget'
  - browser-tools/install-chrome:
            chrome-version: "latest"
```

The installation of chrome shows below error - 
<img width="1158" alt="Screenshot 2022-04-01 at 11 20 09 PM" src="https://user-images.githubusercontent.com/23141842/161316958-17d130dc-78e8-4307-8f0b-e7cb7f195833.png">

### Expected behaviour

Chrome should be installed.
