### ISSUE TITLE
Chrome installation in Mac is taking long

### ISSUE THREAD

**Issue by abhinaba-ghosh** [CircleCI-Public/browser-tools-orb#49]
### Orb version
circleci/browser-tools@1.2.5

### What happened
The browser tool orb takes ~6 minutes to install the chrome in Mac executor while it is taking <1 minute in the Linux executor. Is there a way to bring down the installation time?

```
  macos-executor:
    macos:
      xcode: 13.2.1
    resource_class: macos.x86.medium.gen2
```
