### ISSUE TITLE
Lack of clarity regarding installation caching

### ISSUE THREAD

**Issue by matthewcsnyder** [CircleCI-Public/browser-tools-orb#50]
### Orb version

1.3.0

### What happened

It's not clear to me if browser/tool installations provided by this orb are cached, or whether it is possible to cache them.

All examples of using this orb in a config.yml never wrap it in `restore`/`save_cache` stanzas:

```yaml
    steps:
      - browser-tools/install-chrome
      - checkout
      ...
```

Usually placed at the top of a set of steps, rather than interleaved with cache stanzas.

Is it possible to cache installs of browsers (specifically Chrome for my requirements)? Would it be as simple as (e.g. for apt-based Linuxes) to have something like:

```yaml
    steps:
      - restore_cache:
          name: Restore cache
          keys:
            - v1-my-cache-{{ checksum "yarn.lock" }}
      - browser-tools/install-chrome
      - save_cache
        name: Save cache
        key: v1-my-cache-{{ checksum "yarn.lock" }}
        paths:
            - /usr/bin/google-chrome
       ...
```

Thanks!
