### ISSUE TITLE
Specifying older version of chrome fails to download.

### ISSUE THREAD

**Issue by nanophate** [CircleCI-Public/browser-tools-orb#59]
### Orb version

`circleci/browser-tools@1.2.5`

### What happened

Specifying chrome version fails and accessing to the specified `https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_91.0.4472.77-1_amd64.deb` link returns 404.

https://app.circleci.com/pipelines/github/nanophate/cci-template-dynamic/13/workflows/782e7db8-60d5-4edc-85b3-c9d20e5e0318/jobs/15?invite=true#step-102-139

```
Google Chrome is not currently installed; installing it
curl: (22) The requested URL returned error: 404 
```

```yaml
- browser-tools/install-chrome:
     chrome-version: 91.0.4472.77
     replace-existing: true
```

### Expected behavior

I would expect it to download the specified chrome version.
