### ISSUE TITLE
LICENSE.chromedriver placed in project dir, preventing checkout

### ISSUE THREAD

**Issue by JasonBarnabe** [CircleCI-Public/browser-tools-orb#62]
### Orb version

circleci/browser-tools@1.4.0

### What happened

Starting today, the `checkout` step fails with `Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository`.

```
      - browser-tools/install-browser-tools:
          install-firefox: false
          install-geckodriver: false
(...)
      - checkout
```
 When I ssh in I can see:

```
$ ls /home/circleci/project
LICENSE.chromedriver
```

Which is presumably put there by browser-tools installing Chromedriver.

https://app.circleci.com/pipelines/github/Simplero/Simplero/39438/workflows/1f0f4035-6ed4-4741-a8ce-52cff73d8188/jobs/40291

### Expected behavior

browser-tools should ensure the project directory does not get additional files.

**Comment by JasonBarnabe** [comment]
Workaround: delete the file.

```
      - browser-tools/install-browser-tools:
          install-firefox: false
          install-geckodriver: false
      - run:
          command: rm /home/circleci/project/LICENSE.chromedriver
      - checkout
```
