### ISSUE TITLE
The laster version always install  112.0.5615.49 version

### ISSUE THREAD

**Issue by tranChiVi0123** [CircleCI-Public/browser-tools-orb#84]
### Orb version
1.4.3

- image: cimg/ruby:3.0.6-browsers

```yaml
...
- browser-tools/install-chrome:
    chrome-version: latest or 114.0.5735.9

- browser-tools/install-chromedriver
...
```

### What happened
It always installs `112.0.5615.49`

CircleCi message　↓
```bash
Google Chrome 112.0.5615.49 is already installed to /usr/bin/google-chrome
```
